config/routes.rb
Rails.application.routes.draw do
  get 'users/private_office', as: :private_office
  get 'users/orders', as: :user_orders
  get 'carts/my_cart', as: :my_cart

  get 'products/search', as: :products_search
  get 'products/about', as: :products_about

  resources :user_reviews, only:[:index, :create]
  resources :contacts, only:[:create, :new, :index]
  resources :news_item, only:[:show, :index], path: 'news'
  resources :categories, only:[:show]
  resources :products, only: [:show]
  resources :line_items, only: [:create, :destroy, :update, :index]
  resources :orders, only: [:new, :create, :show]
  post 'line_items/create_in_product', as: :create_line_items_in_product
  root to: 'news_item#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item.price = product.price
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_quantity
    line_items.to_a.sum { |item| item.quantity }
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  def to_param
    "#{id}-#{name.parameterize}"
  end
  has_many :products
  validates :name, :title, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,
            presence: true,
            length: {minimum: 1, maximum: 254}


  validates :email,
            presence: true,
            format: { with: VALID_EMAIL_REGEX },
            length: {minimum: 1, maximum: 254}

  validates :phone,
            presence: true,
            numericality: {only_integer: true}

  validates :message,
            presence: true,
            length: {maximum: 1000, minimum: 1}
end

app/models/currency_value.rb
class CurrencyValue < ActiveRecord::Base
  validates :gbp, :usd, :eur, numericality: true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
  belongs_to :order
  validates :quantity, numericality: { greater_than_or_equal_to: 1, less_than: 100 }
  def total_price
    quantity * price
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  def to_param
    "#{id}-#{title.parameterize}"
  end

  paginates_per 10
  default_scope { order('created_at DESC') }

  has_attached_file :image, :styles => { :medium => "1400x300>", :thumb => "700x150>" },
                    :default_url => "/images/news/:style/missing.jpg",
                    :size => {:in => 0..5.megabyte}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :body, :title, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  default_scope {order('created_at DESC')}
  belongs_to :user
  has_many :line_items
  enum delivery_type: ['Автотрейдин', 'Деловые линии', 'Почта России']
  enum status: ['Обрабатывается', 'Доставка', 'Завершен', 'Отказ' ]

  validates :address,
            presence: true,
            length: {minimum: 1, maximum: 512}
  validates :city, :name, :country, :phone,
            presence: true,
            length: {minimum: 1, maximum: 256}
  validates :delivery_type,
            presence: true
  validates :special,
            length: {maximum: 1024}

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end

  def add_item_from_cart(cart)
    cart.line_items.each do |line_item|
      line_item.cart_id = nil
      line_items << line_item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  def to_param
    "#{id}-#{name.parameterize}"
  end

  include PgSearch
  paginates_per 12
  default_scope {order('updated_at DESC')}
  pg_search_scope :search_by_name_or_article, against: [:name, :article]
  has_many :line_items
  before_destroy :check_line_items
  has_many :additional_descriptions, :dependent => :delete_all
  belongs_to :category
  accepts_nested_attributes_for :additional_descriptions, :allow_destroy => true

  has_attached_file :first_image, :styles => { :medium => "500x435>", :small => "120x120>", :thumb => "360x390>" },
                    :default_url => "/images/products/:style/missing.jpg",
                    :size => {:in => 0..5.megabyte}

  has_attached_file :second_image, :styles => { :medium => "500x435>", :small => "120x120>", :thumb => "360x390>" },
                    :default_url => "/images/products/:style/missing.jpg",
                    :size => {:in => 0..5.megabyte}

  validates_attachment_content_type :first_image, :second_image, :content_type => /\Aimage\/.*\Z/
  validates :name, :article, :price, :description, presence: true
  validates :price, numericality: true

  private

  def check_line_items
    if line_items.empty?
      return true
    else
      errors.add(:base, 'nope!')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :user_reviews
  enum gender: ['Мужской', 'Женский']

  validates :birth_date, :name, :organization, :position, :surname,
            presence: true,
            length: {minimum: 1, maximum: 256}

  validates :birth_date, :gender,
            presence: true

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/user_review.rb
class UserReview < ActiveRecord::Base
  paginates_per 12
  belongs_to :user
  validates :body, presence: true, length: {maximum: 1500}
end

app/models/valute.rb
class Valute < ActiveRecord::Base

	validates :gbp, :usd, :eur, numericality: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def my_cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_currency(price)
    number_to_currency(price, unit: "", separator: ",", delimiter: " ")
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/news_item_helper.rb
module NewsItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_empty_cart.html.slim
p Ваша карзина пуста =(
p Закажите чего-нибудь.

app/views/carts/my_cart.html.slim
= content_for 'header' do
  =javascript_include_tag 'my_cart'
= content_for :title, 'Путьмаш. Моя корзина'
.col-md-2
  == render 'categories/sidebar_categories'
.col-md-8
  h2.text-center Ваша корзина
  .my-cart
    -if @cart.total_quantity == 0
      == render 'carts/empty_cart'
    -else
      .table-responsive
        table.table.table-condensed
          thead
            tr
              th #
              th Название
              th Кол-во
              th Цена
              th
          tbody
            -@cart.line_items.each do |line_item|
              tr id=('line_item_' + line_item.id.to_s)
                td.col-md-2.col-sm-2
                  =image_tag(line_item.product.first_image.url(:small), class: 'thumb-image',  alt: line_item.product.name)
                td.col-md-2.col-sm-2
                  =link_to(line_item.product.name, line_item.product)
                td.col-md-3.col-sm-3
                  .line_item_quantity_block
                    = simple_form_for(line_item, html: {remote: true, class: 'form-inline'}) do |f|
                      = f.button :submit, style: 'display:none;'
                      = f.button :submit, '-', class: :minus
                      = f.input :quantity, as: :string, label: false, input_html: { class: 'qty_form quantity', maxlength: 2}
                      = f.button :submit, '+', class: :plus
                td.total-price.col-md-2.col-sm-2 = number_to_currency(line_item.total_price)
                td.col-md-1.col-sm-1
                  = link_to  line_item, 'method': 'delete', 'remote': true, 'class': 'btn btn-default'
                    span.glyphicon.glyphicon-remove

      h3.cart-total-price.pull-right
        i.bold = number_to_currency(@cart.total_price)
      .clearfix
      -if user_signed_in?
        .btn-group.pull-right
          =link_to 'Перейти к оформлению заказа', new_order_path, class: 'btn btn-primary btn-lg'
      -else
        .cart-reg.pull-right
          =link_to 'Войти и заказать', new_user_session_path, class: 'btn btn-primary btn-lg '
          =link_to 'Зарегистрироваться и заказать', new_user_registration_path, class: 'btn btn-primary btn-lg'
      .clearfix