config/routes.rb
Rails.application.routes.draw do
  get 'users/private_office', as: :private_office
  get 'users/orders', as: :user_orders
  get 'carts/my_cart', as: :my_cart

  get 'products/search', as: :products_search
  get 'products/about', as: :products_about

  resources :user_reviews, only:[:index, :create]
  resources :contacts, only:[:create, :new, :index]
  resources :news_item, only:[:show, :index], path: 'news'
  resources :categories, only:[:show]
  resources :products, only: [:show]
  resources :line_items, only: [:create, :destroy, :update, :index]
  resources :orders, only: [:new, :create, :show]
  post 'line_items/create_in_product', as: :create_line_items_in_product
  root to: 'news_item#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item.price = product.price
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_quantity
    line_items.to_a.sum { |item| item.quantity }
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  def to_param
    "#{id}-#{name.parameterize}"
  end
  has_many :products
  validates :name, :title, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,
            presence: true,
            length: {minimum: 1, maximum: 254}


  validates :email,
            presence: true,
            format: { with: VALID_EMAIL_REGEX },
            length: {minimum: 1, maximum: 254}

  validates :phone,
            presence: true,
            numericality: {only_integer: true}

  validates :message,
            presence: true,
            length: {maximum: 1000, minimum: 1}
end

app/models/currency_value.rb
class CurrencyValue < ActiveRecord::Base
  validates :gbp, :usd, :eur, numericality: true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
  belongs_to :order
  validates :quantity, numericality: { greater_than_or_equal_to: 1, less_than: 100 }
  def total_price
    quantity * price
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  def to_param
    "#{id}-#{title.parameterize}"
  end

  paginates_per 10
  default_scope { order('created_at DESC') }

  has_attached_file :image, :styles => { :medium => "1400x300>", :thumb => "700x150>" },
                    :default_url => "/images/news/:style/missing.jpg",
                    :size => {:in => 0..5.megabyte}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :body, :title, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  default_scope {order('created_at DESC')}
  belongs_to :user
  has_many :line_items
  enum delivery_type: ['Автотрейдин', 'Деловые линии', 'Почта России']
  enum status: ['Обрабатывается', 'Доставка', 'Завершен', 'Отказ' ]

  validates :address,
            presence: true,
            length: {minimum: 1, maximum: 512}
  validates :city, :name, :country, :phone,
            presence: true,
            length: {minimum: 1, maximum: 256}
  validates :delivery_type,
            presence: true
  validates :special,
            length: {maximum: 1024}

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end

  def add_item_from_cart(cart)
    cart.line_items.each do |line_item|
      line_item.cart_id = nil
      line_items << line_item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  def to_param
    "#{id}-#{name.parameterize}"
  end

  include PgSearch
  paginates_per 12
  default_scope {order('updated_at DESC')}
  pg_search_scope :search_by_name_or_article, against: [:name, :article]
  has_many :line_items
  before_destroy :check_line_items
  has_many :additional_descriptions, :dependent => :delete_all
  belongs_to :category
  accepts_nested_attributes_for :additional_descriptions, :allow_destroy => true

  has_attached_file :first_image, :styles => { :medium => "500x435>", :small => "120x120>", :thumb => "360x390>" },
                    :default_url => "/images/products/:style/missing.jpg",
                    :size => {:in => 0..5.megabyte}

  has_attached_file :second_image, :styles => { :medium => "500x435>", :small => "120x120>", :thumb => "360x390>" },
                    :default_url => "/images/products/:style/missing.jpg",
                    :size => {:in => 0..5.megabyte}

  validates_attachment_content_type :first_image, :second_image, :content_type => /\Aimage\/.*\Z/
  validates :name, :article, :price, :description, presence: true
  validates :price, numericality: true

  private

  def check_line_items
    if line_items.empty?
      return true
    else
      errors.add(:base, 'nope!')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :user_reviews
  enum gender: ['Мужской', 'Женский']

  validates :birth_date, :name, :organization, :position, :surname,
            presence: true,
            length: {minimum: 1, maximum: 256}

  validates :birth_date, :gender,
            presence: true

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/user_review.rb
class UserReview < ActiveRecord::Base
  paginates_per 12
  belongs_to :user
  validates :body, presence: true, length: {maximum: 1500}
end

app/models/valute.rb
class Valute < ActiveRecord::Base

	validates :gbp, :usd, :eur, numericality: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.where('featured', true).find(params[:id])
  end

  def about
  end

  def search
    @keyword = params[:search]
    if @keyword.length > 3
      @products = Product.search_by_name_or_article(@keyword).where('featured', true).page(params[:page])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_currency(price)
    number_to_currency(price, unit: "", separator: ",", delimiter: " ")
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        fenced_code_blocks: true,
        lax_html_blocks: true,
        strikethrough: true,
        superscript: true,
        space_after_headers: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/news_item_helper.rb
module NewsItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_reviews_helper.rb
module UserReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_thumb.html.slim
- products.each do |product|
  .col-sm-6.col-md-4
    .thumbnail
      = link_to product
        = image_tag product.first_image.url(:thumb), class: 'img-rounded'
      .caption.cart-desc-container
        p.cart-title
          = link_to product.name, product
        p
          ' артикул:
          strong = product.article
        h4
          ' Цена:
          strong.cart-price = number_to_currency(product.price)

        = link_to 'В корзину', line_items_path(product_id: product.id),
                  'method': 'post', 'remote': true,
                  'class': 'btn-block btn btn-primary to-cart-btn',
                  'id': "#{product.id}-cart-btn"

app/views/products/about.html.slim
=content_for :title, 'Путьмаш. Поиск по сайту...'
.row
  .col-md-2.col-sm-2
    == render 'categories/sidebar_categories'
  .col-md-8.col-md-8
    h2 О продукции:

    p Каталог предложений включает в себя несколько тысяч наименований различных устройств для
      самых разнообразных применений в промышленности, технике и машиностроении. На всё
      оборудование, поставляемое ООО «ПутьмашСеверо-Запад», сохраняются гарантийные
      обязательства производителя.

    p Конкурентоспособные цены, максимально сжатые сроки выполнения заказов и внимательное
      отношение к каждому заказчику являются факторами, обуславливающими выбор в пользу нашей
      фирмы.

    = image_tag 'Rexroth_Service_Products_w486.jpg', alt: 'products'

app/views/products/search.html.slim
=content_for :title, 'Путьмаш. Поиск по сайту...'
.row
  .col-md-2.col-sm-2
    == render 'categories/sidebar_categories'
  .col-md-10.col-md-8
    h2
      ' Поиск по:
      strong = @keyword
    -if @products.blank?
      p Ничего не найдено
    -else
      == render 'products/thumb', products: @products
    .clearfix
    .pull-right
      -unless @products.blank?
        = paginate @products

app/views/products/show.html.slim
=content_for :title, "Путьмаш. #{@product.name}"
ol.breadcrumb
  li
    =link_to 'Домой', root_path
  li
    =link_to @product.category.name, @product.category
  li.active = @product.name
=link_to 'Вернуться', :back, class: 'btn btn-primary'
.row
  .col-sm-6.col-md-6
    h2
      = @product.name
    p
      strong Артикyл:
      '
      = @product.article
    p
      strong Описание:
    p
      = @product.description
    .well.price-well
      strong.price
        = number_to_currency(@product.price)
        = link_to 'В корзину', create_line_items_in_product_path(product_id: @product.id),
                  'method': 'post', 'remote': true,
                  'class': 'btn btn-lg btn-primary pull-right product-to-cart'
      .clearfix
    -unless @product.additional_descriptions.blank?
      h3 Дополнительное описание
      dl.dl-horizontal
        -@product.additional_descriptions.each do |ad|
          dt = ad.name
          dd = ad.value
  .col-sm-6.col-md-6
    -unless @product.first_image.blank?
      = image_tag @product.first_image.url(:medium), class: 'img-rounded show-img'
    -unless @product.second_image.blank?
      = image_tag @product.second_image.url(:medium), class: 'img-rounded show-img'