config/routes.rb
Rails.application.routes.draw do
  get 'users/private_office', as: :private_office
  get 'users/orders', as: :user_orders
  get 'carts/my_cart', as: :my_cart

  get 'products/search', as: :products_search
  get 'products/about', as: :products_about

  resources :user_reviews, only:[:index, :create]
  resources :contacts, only:[:create, :new, :index]
  resources :news_item, only:[:show, :index], path: 'news'
  resources :categories, only:[:show]
  resources :products, only: [:show]
  resources :line_items, only: [:create, :destroy, :update, :index]
  resources :orders, only: [:new, :create, :show]
  post 'line_items/create_in_product', as: :create_line_items_in_product
  root to: 'news_item#index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item.price = product.price
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_quantity
    line_items.to_a.sum { |item| item.quantity }
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  def to_param
    "#{id}-#{name.parameterize}"
  end
  has_many :products
  validates :name, :title, presence: true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,
            presence: true,
            length: {minimum: 1, maximum: 254}


  validates :email,
            presence: true,
            format: { with: VALID_EMAIL_REGEX },
            length: {minimum: 1, maximum: 254}

  validates :phone,
            presence: true,
            numericality: {only_integer: true}

  validates :message,
            presence: true,
            length: {maximum: 1000, minimum: 1}
end

app/models/currency_value.rb
class CurrencyValue < ActiveRecord::Base
  validates :gbp, :usd, :eur, numericality: true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
  belongs_to :order
  validates :quantity, numericality: { greater_than_or_equal_to: 1, less_than: 100 }
  def total_price
    quantity * price
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  def to_param
    "#{id}-#{title.parameterize}"
  end

  paginates_per 10
  default_scope { order('created_at DESC') }

  has_attached_file :image, :styles => { :medium => "1400x300>", :thumb => "700x150>" },
                    :default_url => "/images/news/:style/missing.jpg",
                    :size => {:in => 0..5.megabyte}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :body, :title, presence: true
end

app/models/order.rb
class Order < ActiveRecord::Base
  default_scope {order('created_at DESC')}
  belongs_to :user
  has_many :line_items
  enum delivery_type: ['Автотрейдин', 'Деловые линии', 'Почта России']
  enum status: ['Обрабатывается', 'Доставка', 'Завершен', 'Отказ' ]

  validates :address,
            presence: true,
            length: {minimum: 1, maximum: 512}
  validates :city, :name, :country, :phone,
            presence: true,
            length: {minimum: 1, maximum: 256}
  validates :delivery_type,
            presence: true
  validates :special,
            length: {maximum: 1024}

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end

  def add_item_from_cart(cart)
    cart.line_items.each do |line_item|
      line_item.cart_id = nil
      line_items << line_item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  def to_param
    "#{id}-#{name.parameterize}"
  end

  include PgSearch
  paginates_per 12
  default_scope {order('updated_at DESC')}
  pg_search_scope :search_by_name_or_article, against: [:name, :article]
  has_many :line_items
  before_destroy :check_line_items
  has_many :additional_descriptions, :dependent => :delete_all
  belongs_to :category
  accepts_nested_attributes_for :additional_descriptions, :allow_destroy => true

  has_attached_file :first_image, :styles => { :medium => "500x435>", :small => "120x120>", :thumb => "360x390>" },
                    :default_url => "/images/products/:style/missing.jpg",
                    :size => {:in => 0..5.megabyte}

  has_attached_file :second_image, :styles => { :medium => "500x435>", :small => "120x120>", :thumb => "360x390>" },
                    :default_url => "/images/products/:style/missing.jpg",
                    :size => {:in => 0..5.megabyte}

  validates_attachment_content_type :first_image, :second_image, :content_type => /\Aimage\/.*\Z/
  validates :name, :article, :price, :description, presence: true
  validates :price, numericality: true

  private

  def check_line_items
    if line_items.empty?
      return true
    else
      errors.add(:base, 'nope!')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :orders
  has_many :user_reviews
  enum gender: ['Мужской', 'Женский']

  validates :birth_date, :name, :organization, :position, :surname,
            presence: true,
            length: {minimum: 1, maximum: 256}

  validates :birth_date, :gender,
            presence: true

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/user_review.rb
class UserReview < ActiveRecord::Base
  paginates_per 12
  belongs_to :user
  validates :body, presence: true, length: {maximum: 1500}
end

app/models/valute.rb
class Valute < ActiveRecord::Base

	validates :gbp, :usd, :eur, numericality: true
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/news_item_helper.rb
module NewsItemHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
.container
  .row
    .panel.panel-default.footer-panel
      .panel-body
        .col-sm-3.col-md-3
          p
            | Россия
            br
            | 190068 Санкт-Питербург,
            br
            |Николайский переулок д.4
        .col-sm-3.col-md-3.text-left
          p
            br
            | Тел: (812) 713-74-92
            br
            | Факс: (812) 570-25-90
        .col-sm-6.col-md-6.text-right
          = link_to 'Обратная связь с администрацией сайта', new_contact_path
          br
            = link_to 'https://plus.google.com/communities/111390974052732778103?hl=ru', class: 'btn btn-social-icon btn-google'
              i.fa.fa-google
            = link_to 'http://vk.com/club97012779', class: "btn btn-social-icon btn-vk"
              i.fa.fa-vk
            = link_to 'https://www.facebook.com/pages/%D0%9F%D1%83%D1%82%D1%8C%D0%BC%D0%B0%D1%88-%D0%A1%D0%B5%D0%B2%D0%B5%D1%80-%D0%97%D0%B0%D0%BF%D0%B0%D0%B4/417724771768109', class: 'btn btn-social-icon btn-facebook'
              i.fa.fa-facebook

app/views/layouts/_header.html.slim
.page-header
  .container
    .row
      =link_to my_cart_path, class:'btn btn-default pull-right cart'
        ' Корзина
        .span.glyphicon.glyphicon-shopping-cart
        .badge#product-qty
          = @cart.total_quantity

    .row
      .col-sm-6.col-md-6
        = link_to root_path
          = image_tag 'logo.png', alt: 'logo', class: 'pull-left'
        h3.pull-left.title ПУТЬМАШ СЕВЕРО-ЗАПАД
        .clearfix


      .col-sm-6.col-md-3
        -if user_signed_in?
          .panel.panel-default
            .panel-body
              p
                i  #{current_user.name.capitalize } #{current_user.surname.capitalize}
              strong = current_user.email
              p
                = link_to 'Личный кабинет ', private_office_path
                = link_to 'Выйти', destroy_user_session_path, :method => :delete
        -else
          .panel.panel-default
            .panel-body
              = simple_form_for(resource, as: resource_name, url: session_path(resource_name),
                                html: { class: 'form-horizontal' },
                                wrapper: :horizontal_form,
                                ) do |f|
                = f.input :email, required: false, label: 'Почта'
                = f.input :password, required: false, label: 'Пароль'
                .col-sm-offset-4.remember-me
                  = f.input :remember_me, label: 'Запомнить меня', as: :boolean if devise_mapping.rememberable?
                .btn-group.btn-group-sm
                  = f.button :submit, "Войти"
                  = link_to 'Регистрация',new_user_registration_path, class: 'btn btn-default pull-right'

      .col-sm-3.col-md-3.hidden-xs.hidden-sm
        = link_to 'http://www.cbr.ru', class: 'valutes-info'
          .panel.panel-default.pull-right
            .panel-body
              table.table.table-condensed
                thead
                  tr
                    th #
                    th USD
                    th GBP
                    th EUR
                tbody
                  - currency.reverse_each do |value|
                    tr
                      td = value.created_at.strftime('%F')
                      td = custom_currency value.usd
                      td = custom_currency value.gbp
                      td = custom_currency value.eur
    .row
      .col-sm-6.col-md-6.text-center.nav-panel
        =link_to root_path, class: 'btn btn-primary'
          strong Новости
        =link_to page_path(:about), class: 'btn btn-primary'
          strong О нас
        =link_to products_about_path, class: 'btn btn-primary'
          strong О продукции
        =link_to page_path(:about_orders), class: 'btn btn-primary'
          strong Заказы
        =link_to user_reviews_path, class: 'btn btn-primary'
          strong Отзывы
      .col-md-6.col-sm-6
        .panel.panel-default.search-panel
          .panel-body
            = form_tag products_search_path, method: :get, class: ['form-inline', 'text-right']
              .form-group
                label for='search-inp' Поиск по сайту
                =search_field_tag :search, params[:search], placeholder: 'поиск по названию/марке',
                                  class: 'form-control',
                                  id:'search-inp'
                = submit_tag 'Найти', class: 'btn btn-default'

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Putmash'
    meta name="google-site-verification" content="_3fp1wUXJJDVo7iYg59cOnAIHQkgVwbc-oF_tIYLhh4"
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Putmash'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
    = content_for :header
  body
    header
      == render 'layouts/header', currency: @currency
    main[role="main"]
      .container
        == render 'layouts/messages'
        == yield
    == render 'layouts/footer'

app/views/layouts/devise.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Putmash'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Putmash'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    main[role="main"]
      .container
        .row
          .col-md-offset-4.col-md-4
            .panel.panel-default.devise-panel
              .panel-body
                == render 'layouts/messages'
                = link_to root_path
                  = image_tag('logo.png')
                == yield

app/views/purchase_confirmation/admin_confirmation.html.slim
p = @order.name
p Номер вашего заказа ##{@order.id}
ul
  ' В заказ входят:
  -@order.line_items.each do |line_item|
    li
      = link_to line_item.product.name, line_item.product
      '  #{line_item.quantity} шт. x
      ' #{number_to_currency(line_item.price)} =
      ' #{number_to_currency(line_item.total_price)}

p Общая сумма покупки: #{number_to_currency(@order.total_price)}
p Адрес доставки: #{@order.city}, #{@order.address}
p Способ доставки: #{@order.delivery_type}

app/views/purchase_confirmation/user_confirmation.html.slim
p = @order.name
p Номер вашего заказа ##{@order.id}
ul
  ' В заказ входят:
  -@order.line_items.each do |line_item|
    li
      = link_to line_item.product.name, line_item.product
      '  #{line_item.quantity} шт. x
      ' #{number_to_currency(line_item.price)} =
      ' #{number_to_currency(line_item.total_price)}

p Общая сумма вашей покупки: #{number_to_currency(@order.total_price)}
p Адрес доставки: #{@order.city}, #{@order.address}
p Способ доставки: #{@order.delivery_type}
p В ближайшее время наши сотрудники с вами свяжутся
p Спасибо за покупку, ждем вас снова.